# Generated by Django 5.2.3 on 2025-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="grade_level",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
