# Generated by Django 5.2.3 on 2025-06-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_class_grade_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="classes",
        ),
        migrations.AddField(
            model_name="class",
            name="max_groups",
            field=models.PositiveIntegerField(
                default=6, help_text="Maximum number of groups"
            ),
        ),
    ]
