# Generated by Django 5.2.3 on 2025-06-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_student_classes_class_max_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="max_groups",
        ),
    ]
