# Generated by Django 5.2.3 on 2025-08-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_classroomlayout_classroomtable_layoutobstacle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatingperiod",
            name="layout",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical layout used for this seating period",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seating_periods_using_layout",
                to="students.classroomlayout",
            ),
        ),
    ]
