# Generated by Django 5.2.3 on 2025-08-09 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_backfill_seating_period_layouts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatingperiod",
            name="layout",
            field=models.ForeignKey(
                help_text="Physical layout used for this seating period",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seating_periods_using_layout",
                to="students.classroomlayout",
            ),
        ),
    ]
