# Generated by Django 5.2.3 on 2025-08-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_make_layout_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
