# Generated by Django 5.2.3 on 2025-08-12 11:06

from django.db import migrations, models


def populate_nicknames(apps, schema_editor):
    """Populate nickname field with first_name for existing records"""
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all():
        if not student.nickname:
            student.nickname = student.first_name
            student.save(update_fields=['nickname'])


def reverse_nicknames(apps, schema_editor):
    """Reverse migration - just pass since we're removing the field"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_student_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="nickname",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.RunPython(populate_nicknames, reverse_nicknames),
    ]
