# Generated by Django 5.2.3 on 2025-08-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_student_nickname"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="seatingperiod",
            name="students_se_is_acti_42c047_idx",
        ),
        migrations.RemoveIndex(
            model_name="seatingperiod",
            name="students_se_class_a_460cae_idx",
        ),
        migrations.RemoveField(
            model_name="seatingperiod",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="student",
            name="nickname",
            field=models.CharField(max_length=30),
        ),
        migrations.AddIndex(
            model_name="seatingperiod",
            index=models.Index(fields=["class_assigned", "end_date"], name="students_se_class_a_c0aa8e_idx"),
        ),
    ]
