# Generated by Django 5.2.3 on 2025-08-15 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_ensure_end_date_consistency"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnershipRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (-2, "Never Together"),
                            (-1, "Negative"),
                            (0, "Neutral"),
                            (1, "Positive"),
                            (2, "Always Together"),
                        ],
                        default=0,
                        help_text="Rating of how well these students work together",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, help_text="Optional notes about this partnership")),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnership_ratings",
                        to="students.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_partnership_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnership_ratings_as_student1",
                        to="students.student",
                    ),
                ),
                (
                    "student2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnership_ratings_as_student2",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partnership Rating",
                "verbose_name_plural": "Partnership Ratings",
                "ordering": ["class_assigned", "student1", "student2"],
                "indexes": [
                    models.Index(fields=["class_assigned", "student1"], name="students_pa_class_a_6bdc23_idx"),
                    models.Index(fields=["class_assigned", "student2"], name="students_pa_class_a_a8ea80_idx"),
                    models.Index(fields=["class_assigned", "rating"], name="students_pa_class_a_e25fb6_idx"),
                ],
                "unique_together": {("class_assigned", "student1", "student2")},
            },
        ),
    ]
