# Generated by Django 5.2.3 on 2025-08-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_partnershiprating"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomlayout",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Soft delete flag - False means layout is deleted"),
        ),
    ]
