# Generated by Django 5.2.3 on 2025-08-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_classroomlayout_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("tardy", "Tardy"),
                            ("early_dismissal", "Early Dismissal"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes about this attendance record")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.classroster",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "class_roster__student__last_name", "class_roster__student__first_name"],
                "indexes": [
                    models.Index(fields=["date"], name="students_at_date_ad4af7_idx"),
                    models.Index(fields=["class_roster", "date"], name="students_at_class_r_81e050_idx"),
                    models.Index(fields=["status"], name="students_at_status_d4ab0b_idx"),
                ],
                "unique_together": {("class_roster", "date")},
            },
        ),
    ]
