# Generated by Django 5.2.3 on 2025-09-25 00:15

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleClassroomCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField(help_text='Google OAuth access token (encrypted)')),
                ('refresh_token', encrypted_model_fields.fields.EncryptedCharField(help_text='Google OAuth refresh token (encrypted)')),
                ('token_expiry', models.DateTimeField(help_text='When the access token expires')),
                ('scopes', models.JSONField(default=list, help_text='OAuth scopes granted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Classroom Credentials',
                'verbose_name_plural': 'Google Classroom Credentials',
                'indexes': [models.Index(fields=['user', 'token_expiry'], name='students_go_user_id_efc40f_idx')],
            },
        ),
    ]
