# Generated by Django 5.2.3 on 2025-12-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_googleclassroomcredentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="google_user_id",
            field=models.CharField(
                blank=True, help_text="Google Workspace User ID for Classroom integration", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="preferential_seating",
            field=models.BooleanField(
                default=False, help_text="Student requires preferential seating (e.g., front of room, near teacher)"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["preferential_seating"], name="students_st_prefere_2b6f6c_idx"),
        ),
    ]
