# Generated by Django 5.2.3 on 2026-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_student_google_user_id_student_preferential_seating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layoutobstacle",
            name="obstacle_type",
            field=models.CharField(
                choices=[
                    ("teacher_desk", "Teacher Desk"),
                    ("supply_table", "Supply Table"),
                    ("cabinet", "Cabinet"),
                    ("bookshelf", "Bookshelf"),
                    ("door", "Door"),
                    ("window", "Window"),
                    ("whiteboard", "Whiteboard"),
                    ("projector", "Projector"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
