# Generated by Django 5.2.3 on 2026-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_alter_layoutobstacle_obstacle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatingperiod",
            name="is_tracked",
            field=models.BooleanField(
                default=True,
                help_text="Untracked periods are one-off charts: excluded from partnership history and from the single-current-period rule",
            ),
        ),
    ]
