# Generated by Django 5.2.3 on 2026-07-09 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_seatingperiod_is_tracked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('preferential_seating', models.BooleanField(default=False, help_text='Student requires preferential seating (e.g., front of room, near teacher)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_prefere_2b6f6c_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='preferential_seating',
        ),
        migrations.AddField(
            model_name='student',
            name='cohort',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_annotations', to='students.student'),
        ),
        migrations.AddField(
            model_name='teacherstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacherstudent',
            index=models.Index(fields=['teacher', 'is_active'], name='students_te_teacher_602ebe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstudent',
            unique_together={('teacher', 'student')},
        ),
    ]
