# Generated by Django 5.2.3 on 2026-07-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_backfill_student_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, help_text='Set for student accounts; links to the global Student row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='students.student'),
        ),
    ]
