# Generated by Django 5.2.3 on 2026-07-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_user_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='survey_closes_at',
            field=models.DateTimeField(blank=True, help_text='Optional end of the survey window (blank = no upper bound)', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='survey_enabled',
            field=models.BooleanField(default=False, help_text='Whether the student partner survey is open for this class'),
        ),
        migrations.AddField(
            model_name='class',
            name='survey_opens_at',
            field=models.DateTimeField(blank=True, help_text='Optional start of the survey window (blank = no lower bound)', null=True),
        ),
        migrations.CreateModel(
            name='StudentPartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.SmallIntegerField(choices=[(1, 'Works well'), (-1, "Doesn't work well")])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preferences', to='students.class')),
                ('student', models.ForeignKey(help_text='The student expressing the preference (the chooser)', on_delete=django.db.models.deletion.CASCADE, related_name='partner_preferences_made', to='students.student')),
                ('target', models.ForeignKey(help_text='The classmate the preference is about', on_delete=django.db.models.deletion.CASCADE, related_name='partner_preferences_received', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['class_assigned', 'student'], name='students_st_class_a_f0e2d5_idx')],
                'unique_together': {('class_assigned', 'student', 'target')},
            },
        ),
    ]
