# Generated by Django 5.2.3 on 2026-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0023_class_survey_closes_at_class_survey_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Archived classes are hidden from class lists"),
        ),
    ]
