[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | myenv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | node_modules
  | staticfiles
)/
'''

[tool.isort]
profile = "black"
line_length = 120
skip = ["migrations", "myenv", "venv", ".venv", "node_modules"]
skip_glob = ["*/migrations/*"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
split_on_trailing_comma = true
